name: Build and Push Pokeneas image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKER_PASS: ${{ secrets.DOCKERHUB_PASS }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag juansejb/pokenea:latest

    - name: Push Docker image
      run: docker push juansejb/pokenea:latest

